from __future__ import annotations
import json
import logging
from schemas.state import DesignState
from agents.base import AgentProtocol
from utils.llm_utils import call_llm

class CriticAgent(AgentProtocol):
    def __init__(
        self,
        api_key: str | None,
        model_name: str,
        api_base: str | None = None,
        **kwargs
    ):
        self.api_key = api_key
        self.model_name = model_name
        self.api_base = api_base
        self.kwargs = kwargs

    def run(self, state: DesignState) -> DesignState:
        node = None
        if state.current_node_id and state.current_node_id in state.tree_nodes:
            node = state.tree_nodes[state.current_node_id]
            
        proposals = []
        if node:
            proposals = node.logic_proposals
            best_topo = node.best_topology
        else:
            proposals = state.logic_proposals
            best_topo = state.best_topology

        system_prompt = """You are a rigorous Synthetic Biology Critic Agent.
Your job is to evaluate the Builder's logic proposal and the generated topology's ODE simulation score.
If the logic is incorrect, specify LOGIC_ERROR.
If the logic is correct but the physical constraints, parts, or ODE simulation score is poor or mapping failed, specify PART_ERROR.
If both are problematic, specify BOTH.
If everything is perfect and simulation score > 0.8, specify NONE and set is_approved to True.

You MUST output ONLY a valid JSON object matching this schema:
{
  "reasoning": "Step-by-step analysis",
  "is_approved": false,
  "error_type": "LOGIC_ERROR | PART_ERROR | BOTH | NONE",
  "feedback": "Specific instructions for Builder or Translator"
}
"""
        user_content = f"Original Intent: {state.user_intent}\n"
        user_content += f"Logic Proposals: {proposals}\n"
        if best_topo:
            user_content += f"Best Topology Mapping: {best_topo}\n"
        else:
            user_content += "No valid mapping topologies were generated by Cello/ODE Simulator.\n"
            
        response = call_llm(
            api_key=self.api_key,
            model_name=self.model_name,
            system_prompt=system_prompt,
            user_content=user_content,
            api_base=self.api_base,
            temperature=0.1
        )
        
        try:
            start = response.find("{")
            end = response.rfind("}")
            if start != -1 and end != -1:
                data = json.loads(response[start : end + 1])
                is_approved = data.get("is_approved", False)
                error_type = data.get("error_type", "BOTH")
                feedback = data.get("feedback", "No feedback provided.")
                
                if node:
                    node.is_approved = is_approved
                    node.error_type = error_type
                    node.critic_feedbacks.append(feedback)
                else:
                    state.is_approved = is_approved
                    state.error_type = error_type
                    state.critic_feedbacks.append(feedback)
            else:
                logging.error("Critic output is not JSON.")
                if node:
                    node.error_type = "BOTH"
                    node.critic_feedbacks.append("Critic evaluation failed.")
        except Exception as exc:
            logging.error(f"Critic JSON parse error: {exc}")
            if node:
                node.error_type = "BOTH"
                node.critic_feedbacks.append("Critic evaluation parsing failed.")

        return state
